// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcZKu12yTUTZ1CQcZGqrQsbt_JNI4_4U',
    appId: '1:978347141837:web:21a5cf1c80198db0a51784',
    messagingSenderId: '978347141837',
    projectId: 'glassnik-103a6',
    authDomain: 'glassnik-103a6.firebaseapp.com',
    storageBucket: 'glassnik-103a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWY_E1tRjrDZOI2jSO_4gbXQjGGtzgFT0',
    appId: '1:978347141837:android:21b23299a84ffb68a51784',
    messagingSenderId: '978347141837',
    projectId: 'glassnik-103a6',
    storageBucket: 'glassnik-103a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbZn_wk15Pcah-4PEgW4p4KmEHFupn7S8',
    appId: '1:978347141837:ios:cd180393eac8f592a51784',
    messagingSenderId: '978347141837',
    projectId: 'glassnik-103a6',
    storageBucket: 'glassnik-103a6.firebasestorage.app',
    iosBundleId: 'com.example.glassnik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbZn_wk15Pcah-4PEgW4p4KmEHFupn7S8',
    appId: '1:978347141837:ios:cd180393eac8f592a51784',
    messagingSenderId: '978347141837',
    projectId: 'glassnik-103a6',
    storageBucket: 'glassnik-103a6.firebasestorage.app',
    iosBundleId: 'com.example.glassnik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjcZKu12yTUTZ1CQcZGqrQsbt_JNI4_4U',
    appId: '1:978347141837:web:47be5c0307768965a51784',
    messagingSenderId: '978347141837',
    projectId: 'glassnik-103a6',
    authDomain: 'glassnik-103a6.firebaseapp.com',
    storageBucket: 'glassnik-103a6.firebasestorage.app',
  );
}
