// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByVHC-kNXGm_Oy9tZ5XTW6bTiAyUmyaxA',
    appId: '1:304209189238:web:977a3004c5e839767b4257',
    messagingSenderId: '304209189238',
    projectId: 'glassnik-a1c23',
    authDomain: 'glassnik-a1c23.firebaseapp.com',
    storageBucket: 'glassnik-a1c23.firebasestorage.app',
    measurementId: 'G-9K1MYZHQ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB34BYv0OgElY_AqQTHoDJCMTIBXZQ085o',
    appId: '1:304209189238:android:6db1a048369d4b0f7b4257',
    messagingSenderId: '304209189238',
    projectId: 'glassnik-a1c23',
    storageBucket: 'glassnik-a1c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANl2s3TT5uQkDAoYR4En5SPSd5oyU5HR8',
    appId: '1:304209189238:ios:c79e227387f61af47b4257',
    messagingSenderId: '304209189238',
    projectId: 'glassnik-a1c23',
    storageBucket: 'glassnik-a1c23.firebasestorage.app',
    iosBundleId: 'com.example.glassnik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANl2s3TT5uQkDAoYR4En5SPSd5oyU5HR8',
    appId: '1:304209189238:ios:c79e227387f61af47b4257',
    messagingSenderId: '304209189238',
    projectId: 'glassnik-a1c23',
    storageBucket: 'glassnik-a1c23.firebasestorage.app',
    iosBundleId: 'com.example.glassnik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByVHC-kNXGm_Oy9tZ5XTW6bTiAyUmyaxA',
    appId: '1:304209189238:web:efe0e13cfd6e928d7b4257',
    messagingSenderId: '304209189238',
    projectId: 'glassnik-a1c23',
    authDomain: 'glassnik-a1c23.firebaseapp.com',
    storageBucket: 'glassnik-a1c23.firebasestorage.app',
    measurementId: 'G-P2X5FR4G9Y',
  );
}
